pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
               sh 'cd coit-backend1 && mvn install'
            }
        }
        stage('docker-build') {
            steps {
               sh 'cd coit-backend1 && docker build -t danushvithiyarth/coit-backend1:v2 .'
               sh 'docker images' 
            }
        }
        stage('docker-push') {
           steps {
              withCredentials([usernamePassword(credentialsId: '9744ba9d-bc79-4d74-9699-adb4045f16c5', usernameVariable: 'danushvithiyarth', passwordVariable: 'fodjo1-qatgoP-fixsyq')]) {
                    sh 'echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin'
                    sh 'docker push danushvithiyarth/coit-backend1:v2'
           }
    }
}
}
}
